spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
  mvc:
    favicon:
      enabled: false
  redis:
    host: 101.132.44.128
    port: 6380
    password: wt931201.
  rabbitmq:
    addresses: 101.132.44.128
    port: 5672
    username: wt
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tt.study.demo.entity
logging:
  level:
    com.tt.study.demo.mapper: debug